name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: espressif/idf-rust:esp32c6_latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME}}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      env:
          ENV: development
          GITHUB_WORKSPACE: /home/esp
      ports:
        - 80
        - 443
      volumes:
        - my_docker_volume:/home/esp
      options:
        --cpus 2
        --user root

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
